# Generated by Django 3.2.7 on 2024-04-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityrecordpostcomment',
            old_name='activity_record',
            new_name='post',
        ),
    ]
