# Generated by Django 3.2.7 on 2024-04-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_activity_record_activityrecordpostcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpostimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.clubpost'),
        ),
        migrations.AlterField(
            model_name='eventpostimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.eventpost'),
        ),
    ]
