# Generated by Django 3.2.7 on 2024-04-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_activity_follow'),
        ('activity', '0031_alter_activityrecord_avg_heart_rate'),
        ('social', '0005_auto_20240418_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post_likes', to='social.eventpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post_likes', to='account.activity')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_post_likes', to='social.clubpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_post_likes', to='account.activity')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityRecordPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_rec_post_likes', to='activity.activityrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_rec_post_likes', to='account.activity')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubpost',
            name='likes',
            field=models.ManyToManyField(blank=True, through='social.ClubPostLike', to='account.Activity'),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='likes',
            field=models.ManyToManyField(blank=True, through='social.EventPostLike', to='account.Activity'),
        ),
    ]
