# Generated by Django 3.2.7 on 2024-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20240419_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpost',
            name='total_comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clubpost',
            name='total_likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='total_comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='total_likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
