# Generated by Django 3.2.7 on 2024-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20240427_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpost',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
