# Generated by Django 3.2.7 on 2024-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20240429_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
