# Generated by Django 3.2.7 on 2024-04-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20240429_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
