# Generated by Django 3.2.7 on 2024-05-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20240503_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-created_at',)},
        ),
    ]
