# Generated by Django 3.2.7 on 2024-05-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20240504_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpost',
            name='total_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clubpost',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='total_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
