# Generated by Django 3.2.7 on 2024-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20240505_1038'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityrecordpostlike',
            index=models.Index(fields=['post', 'user'], name='social_acti_post_id_100bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='clubpostlike',
            index=models.Index(fields=['post', 'user'], name='social_club_post_id_a10b76_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpostlike',
            index=models.Index(fields=['post', 'user'], name='social_even_post_id_19a966_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'followee'], name='social_foll_followe_a439d6_idx'),
        ),
    ]
