# Generated by Django 3.2.7 on 2024-04-19 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
