# Generated by Django 3.2.7 on 2024-03-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='clubs', through='activity.UserParticipationClub', to='activity.Club'),
        ),
        migrations.AddField(
            model_name='activity',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', through='activity.UserParticipationEvent', to='activity.Event'),
        ),
        migrations.AddField(
            model_name='activity',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.UserProduct', to='product.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
