# Generated by Django 3.2.7 on 2024-04-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='activity_privacy',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('FOLLOWER', 'Follower'), ('ONLY_ME', 'Only me')], max_length=20),
        ),
    ]
