# Generated by Django 3.2.7 on 2024-04-05 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_privacy_activity_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_workout', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('mentions_on_activities', models.BooleanField(default=False)),
                ('respond_to_comments', models.BooleanField(default=False)),
                ('new_follower', models.BooleanField(default=False)),
                ('following_activity', models.BooleanField(default=False)),
                ('request_to_follow', models.BooleanField(default=False)),
                ('approved_follow_request', models.BooleanField(default=False)),
                ('pending_join_requests', models.BooleanField(default=False)),
                ('invited_to_club', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
