# Generated by Django 3.2.7 on 2024-05-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20240504_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='total_activity_records',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
