# Generated by Django 3.2.7 on 2024-05-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_activity_total_activity_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='total_activity_records',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_followees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
