# Generated by Django 3.2.7 on 2024-03-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_event_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_group',
        ),
        migrations.AddField(
            model_name='event',
            name='competition',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], default='INDIVIDUAL', max_length=15),
        ),
    ]
