# Generated by Django 3.2.7 on 2024-04-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20240401_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparticipationgroup',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userparticipationgroup',
            name='is_approved',
        ),
    ]
