# Generated by Django 3.2.7 on 2024-03-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20240317_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_information',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
