# Generated by Django 3.2.7 on 2024-03-17 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_event_contact_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact_information',
        ),
        migrations.AddField(
            model_name='event',
            name='contactInformation',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500, 'The field can contain at most 200 characters')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1500, 'The field can contain at most 200 characters')]),
        ),
    ]
