# Generated by Django 3.2.7 on 2024-03-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20240317_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='contactInformation',
            new_name='contact_information',
        ),
    ]
