# Generated by Django 3.2.7 on 2024-04-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20240401_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userparticipationclub',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userparticipationevent',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userparticipationgroup',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
