# Generated by Django 3.2.7 on 2024-03-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_rename_contactinformation_event_contact_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticipationevent',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
