# Generated by Django 3.2.7 on 2024-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20240402_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=108, null=True),
        ),
    ]
