# Generated by Django 3.2.7 on 2024-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_activityrecord_avg_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=142, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='completed_at',
            field=models.DateTimeField(),
        ),
    ]
