# Generated by Django 3.2.7 on 2024-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_userparticipationevent_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
