# Generated by Django 3.2.7 on 2024-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20240325_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cover_photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
