# Generated by Django 3.2.7 on 2024-03-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20240325_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='organization',
            field=models.CharField(choices=[('SPORT_CLUB', 'Sport Club'), ('COMPANY', 'Company'), ('SCHOOL', 'School')], default='', max_length=15),
        ),
    ]
