# Generated by Django 3.2.7 on 2024-04-04 05:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_activityrecord_avg_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='privacy',
            field=models.CharField(choices=[('ANYONE', 'Anyone'), ('FOLLOWERS', 'Followers'), ('ONLY_ME', 'Only me')], default='ANYONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=117, null=True),
        ),
        migrations.CreateModel(
            name='ActivityRecordImage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_record_images', to='activity.activityrecord')),
            ],
        ),
    ]
