# Generated by Django 3.2.7 on 2024-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_club_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completion_goal',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ranking_type',
            field=models.CharField(choices=[('DISTANCE', 'Distance'), ('TOTAL_TIME', 'Total time')], default='DISTANCE', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='total_accumulated_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='total_money_donated',
            field=models.BooleanField(default=False),
        ),
    ]
