# Generated by Django 3.2.7 on 2024-03-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_accumulated_distance',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_money_donated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
