# Generated by Django 3.2.7 on 2024-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20240326_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='donated_money_exchange',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=5),
        ),
    ]
