# Generated by Django 3.2.7 on 2024-04-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20240405_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=155, null=True),
        ),
    ]
