# Generated by Django 3.2.7 on 2024-04-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_alter_activityrecord_avg_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=113, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
