# Generated by Django 3.2.7 on 2024-04-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_auto_20240413_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=157, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
