# Generated by Django 3.2.7 on 2024-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_auto_20240418_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=132, null=True),
        ),
    ]
