# Generated by Django 3.2.7 on 2024-04-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0034_auto_20240419_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=132, null=True),
        ),
    ]
