# Generated by Django 3.2.7 on 2024-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0039_alter_activityrecord_avg_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='total_comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='total_likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=132, null=True),
        ),
    ]
