# Generated by Django 3.2.7 on 2024-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_auto_20240427_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=106, null=True),
        ),
    ]
