# Generated by Django 3.2.7 on 2024-04-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0043_auto_20240429_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=107, null=True),
        ),
    ]
