# Generated by Django 3.2.7 on 2024-05-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0048_alter_activityrecord_avg_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='total_participants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_participants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=124, null=True),
        ),
    ]
