# Generated by Django 3.2.7 on 2024-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0049_auto_20240503_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_participants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=157, null=True),
        ),
    ]
