# Generated by Django 3.2.7 on 2024-05-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0050_auto_20240503_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=122, null=True),
        ),
    ]
