# Generated by Django 3.2.7 on 2024-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0055_auto_20240505_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='avg_heart_rate',
            field=models.IntegerField(default=138, null=True),
        ),
        migrations.AddIndex(
            model_name='userparticipationclub',
            index=models.Index(fields=['user', 'club'], name='activity_us_user_id_d48ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='userparticipationevent',
            index=models.Index(fields=['user', 'event'], name='activity_us_user_id_bd17cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userparticipationgroup',
            index=models.Index(fields=['user', 'group'], name='activity_us_user_id_0fe556_idx'),
        ),
    ]
